### ISSUE TITLE
Canvas does not respect window.devicePixelRatio

### ISSUE THREAD

**Issue by benwiles1** [CesiumGS/cesium#8699]
Sandcastle example: any

Browser: Chrome

Operating System: Windows 7

I have a device pixel ratio of 1.25
when i add the CSS
```CSS
.cesium-widget canvas {
    width: 100px;
    height: 100px;
}
```
The canvas' width and height get set to 100, but it should be getting set to 125.
